# Site settings
title: 我有分寸
email: gnawux@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    忽然不想维持多年的 Wordpress Blog 了，停了虚拟主机，省点银子，直接
    host 在 GitHub 上好了。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: gnawux
github_username:  gnawux

# Build settings
markdown: kramdown
